# Diccionario EN -> ES para busquedas en supermercados españoles

EN_TO_ES = {
    # Lácteos
    "milk": "leche",
    "whole milk": "leche entera",
    "semi skimmed milk": "leche semidesnatada",
    "skimmed milk": "leche desnatada",
    "lactose free milk": "leche sin lactosa",
    "condensed milk": "leche condensada",
    "oat milk": "bebida de avena",
    "soy milk": "bebida de soja",
    "almond milk": "bebida de almendras",
    "yogurt": "yogur",
    "greek yogurt": "yogur griego",
    "cream": "nata",
    "cooking cream": "nata para cocinar",
    "whipping cream": "nata para montar",
    "butter": "mantequilla",
    "cheese": "queso",
    "fresh cheese": "queso fresco",
    "grated cheese": "queso rallado",
    "sliced cheese": "queso en lonchas",
    "cream cheese": "queso crema",
    "mozzarella": "mozzarella",
    # Huevos
    "eggs": "huevos",
    "free range eggs": "huevos camperos",
    "organic eggs": "huevos ecológicos",
    # Panadería
    "bread": "pan",
    "sliced bread": "pan de molde",
    "wholemeal bread": "pan integral",
    "breadcrumbs": "pan rallado",
    "toast": "tostadas",
    "baguette": "baguette",
    "croissant": "croissant",
    "burger bun": "pan de hamburguesa",
    # Arroz y pasta
    "rice": "arroz",
    "white rice": "arroz blanco",
    "brown rice": "arroz integral",
    "basmati rice": "arroz basmati",
    "pasta": "pasta",
    "spaghetti": "pasta espaguetis",
    "macaroni": "pasta macarrones",
    "penne": "pasta penne",
    "wholemeal pasta": "pasta integral",
    # Legumbres
    "lentils": "lentejas",
    "chickpeas": "garbanzos",
    "white beans": "alubias blancas",
    "peas": "guisantes",
    # Aceites
    "olive oil": "aceite de oliva",
    "extra virgin olive oil": "aceite de oliva virgen extra",
    "sunflower oil": "aceite de girasol",
    "vinegar": "vinagre",
    # Especias
    "salt": "sal",
    "pepper": "pimienta negra",
    "paprika": "pimentón",
    "oregano": "orégano",
    "cinnamon": "canela",
    "curry": "curry",
    # Azúcar
    "sugar": "azúcar",
    "brown sugar": "azúcar moreno",
    "honey": "miel",
    "jam": "mermelada",
    "strawberry jam": "mermelada de fresa",
    # Harinas
    "flour": "harina",
    "wheat flour": "harina de trigo",
    "yeast": "levadura",
    # Desayuno
    "cocoa": "cacao en polvo",
    "cereals": "cereales de desayuno",
    "oats": "copos de avena",
    "oatmeal": "copos de avena",
    "nutella": "crema de cacao",
    "chocolate spread": "crema de cacao",
    "biscuits": "galletas",
    "cookies": "galletas",
    # Carne
    "chicken breast": "pechuga de pollo",
    "chicken thighs": "muslos de pollo",
    "whole chicken": "pollo entero",
    "chicken": "pollo",
    "beef steak": "filete de ternera",
    "minced meat": "carne picada",
    "ground beef": "carne picada",
    "pork loin": "lomo de cerdo",
    "ribs": "costillas de cerdo",
    "bacon": "bacon",
    "meat": "carne",
    # Charcutería
    "cooked ham": "jamón cocido",
    "ham": "jamón",
    "serrano ham": "jamón serrano",
    "chorizo": "chorizo",
    "salami": "salchichón",
    "mortadella": "mortadela",
    "sausages": "salchichas",
    # Pescado
    "hake": "merluza",
    "salmon": "salmón",
    "tuna": "atún en lata",
    "sardines": "sardinas en lata",
    "cod": "bacalao",
    "prawns": "gambas",
    "shrimp": "gambas",
    "mussels": "mejillones en lata",
    "fish": "pescado",
    # Conservas
    "tomato sauce": "tomate frito",
    "crushed tomatoes": "tomate triturado",
    "canned tomatoes": "tomate natural pelado",
    "sweetcorn": "maíz dulce en lata",
    "corn": "maíz dulce",
    "olives": "aceitunas",
    "chicken stock": "caldo de pollo",
    "vegetable stock": "caldo de verduras",
    # Salsas
    "mayonnaise": "mayonesa",
    "ketchup": "ketchup",
    "mustard": "mostaza",
    "barbecue sauce": "salsa barbacoa",
    "soy sauce": "salsa de soja",
    # Fruta
    "apple": "manzana",
    "orange": "naranja",
    "banana": "plátano",
    "pear": "pera",
    "grapes": "uvas",
    "strawberries": "fresas",
    "peach": "melocotón",
    "watermelon": "sandía",
    "lemon": "limón",
    "kiwi": "kiwi",
    "mandarin": "mandarina",
    "fruit": "fruta",
    # Verdura
    "tomato": "tomate",
    "onion": "cebolla",
    "garlic": "ajo",
    "potato": "patata",
    "potatoes": "patatas",
    "carrot": "zanahoria",
    "red pepper": "pimiento rojo",
    "green pepper": "pimiento verde",
    "pepper": "pimiento",
    "lettuce": "lechuga",
    "spinach": "espinacas",
    "broccoli": "brócoli",
    "cucumber": "pepino",
    "courgette": "calabacín",
    "zucchini": "calabacín",
    "mushrooms": "champiñones",
    "vegetables": "verduras",
    # Bebidas
    "water": "agua mineral",
    "sparkling water": "agua con gas",
    "orange juice": "zumo de naranja",
    "apple juice": "zumo de manzana",
    "cola": "refresco de cola",
    "soda": "refresco",
    "beer": "cerveza",
    "non alcoholic beer": "cerveza sin alcohol",
    "red wine": "vino tinto",
    "white wine": "vino blanco",
    "juice": "zumo",
    # Café
    "coffee": "café molido",
    "instant coffee": "café soluble",
    "coffee capsules": "cápsulas de café",
    "black tea": "té negro",
    "green tea": "té verde",
    "chamomile": "manzanilla",
    "tea": "té",
    # Hogar
    "kitchen paper": "papel de cocina",
    "toilet paper": "papel higiénico",
    "bin bags": "bolsas de basura",
    "cling film": "film transparente",
    "foil": "papel de aluminio",
    "aluminium foil": "papel de aluminio",
    # Limpieza
    "washing powder": "detergente lavadora",
    "detergent": "detergente lavadora",
    "fabric softener": "suavizante",
    "dishwasher liquid": "lavavajillas líquido",
    "dishwasher tablets": "pastillas lavavajillas",
    "bleach": "lejía",
    "cleaning spray": "limpiador multiusos",
    # Higiene
    "shower gel": "gel de ducha",
    "shampoo": "champú",
    "toothpaste": "pasta de dientes",
    "deodorant": "desodorante",
    "hand soap": "jabón de manos",
    # Dulces y snacks
    "dark chocolate": "chocolate negro",
    "milk chocolate": "chocolate con leche",
    "white chocolate": "chocolate blanco",
    "chocolate": "chocolate",
    "crisps": "patatas fritas",
    "chips": "patatas fritas",
    "almonds": "almendras",
    "peanuts": "cacahuetes",
    "walnuts": "nueces",
    # Congelados
    "frozen pizza": "pizza congelada",
    "frozen vegetables": "verduras congeladas",
    "ice cream": "helado",
    "vanilla ice cream": "helado de vainilla",
}

def traducir(query: str) -> str:
    """Traduce término de búsqueda EN->ES si aplica, sino devuelve igual"""
    q = query.strip().lower()
    return EN_TO_ES.get(q, query)
